---
title: " "
pagetitle: "Emily C. Zabor"
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicicons/css/academicons.min.css"/>

## Clinical trials

Appropriate clinical trial designs are essential to the testing of new therapeutics in oncology. New discoveries in cancer biology have shifted some focus away from chemotherapeutic drugs and toward biomarker-targeted treatments and immunotherapies. As a result, novel statistical approaches are needed.

### Selected publications

**Zabor, E. C.**, Kaizer, A. M., Garrett-Mayer, E. & Hobbs, B. P. (Accepted, pending publication). Optimal
sequential predictive probability designs for early phase oncology expansion cohorts.

Hobbs, B. P., Pestana, R. C., **Zabor, E. C.**, Kaizer, A. M., & Hong, D. S. (Accepted, pending publication). Basket trials: review of current practice and innovations for future trials.

**Zabor, E. C.**, Hobbs, B. P., Kane, M. J. (Under review). ppseq: An R Package for Sequential Predictive Probability Monitoring.

Kaizer, A. M., **Zabor, E. C.**, Nie, L. & Hobbs, B. P. (Revise & resubmit). Bayesian and
Frequentist approaches to sequential monitoring for futility in oncology basket trials: A
comparison of Simon’s two-stage design and Bayesian predictive probability monitoring with
information sharing across baskets.

**Zabor, E. C.**, Kane, M. J., Roychoudhury, S., Nie, L., & Hobss, B. P. (2022).
Bayesian Basket Trial Design with False Discovery Rate Control. *Clin Trials*, 17407745211073624. doi:10.1177/17407745211073624

**Zabor, E. C.**, Kaizer, A. M., & Hobbs, B. P. (2020). Randomized Controlled Trials. *Chest*, 158(1s), S79-s87. doi:10.1016/j.chest.2020.03.013

**Zabor, E. C.**, Heller, G., Schwartz, L. H., & Chapman, P. B. (2016). Correlating Surrogate Endpoints with Overall Survival at the Individual Patient Level in BRAFV600E-Mutated Metastatic Melanoma Patients Treated with Vemurafenib. *Clin Cancer Res*, 22(6), 1341-1347. doi:10.1158/1078-0432.ccr-15-1441


## Observational studies

In a hospital setting it is natural to take advantage of the large quantities of data available through electronic health records to conduct retrospective data analyses. Careful thought is needed when applying statistical methods to ensure accurate and interpretable results.

### Selected publications

Eaton, A. A.* and **Zabor, E. C.*** (2022). Analysis of Composite Endpoints with Component-Wise Censoring in the Presence of Differential Visit Schedules. *Stat Med*. doi:10.1002/sim.9312
*equally contributing authors


**Zabor, E. C.**, Reddy, C. A., Tendulkar, R. D., & Patil, S. (2022). Logistic Regression in Clinical Studies. *Int J Radiat Oncol Biol Phys*, 112(2), 271-277. doi:10.1016/j.ijrobp.2021.08.007

**Zabor, E. C.**, Coit, D., Gershenwald, J. E., McMasters, K. M., Michaelson, J. S., Stromberg, A. J., & Panageas, K. S. (2018). Variability in Predictions from Online Tools: A Demonstration Using Internet-Based Melanoma Predictors. *Ann Surg Oncol*, 25(8), 2172-2177. doi:10.1245/s10434-018-6370-4

**Zabor, E. C.**, Gonen, M., Chapman, P. B., & Panageas, K. S. (2013). Dynamic prognostication using conditional survival estimates. *Cancer*, 119(20), 3589-3592. doi:10.1002/cncr.28273


## Etiologic heterogeneity

My dissertation research, under the advisement of [Dr. Shuang Wang](https://www.mailman.columbia.edu/people/our-faculty/sw2206) at Columbia University and [Dr. Colin Begg](https://www.mskcc.org/profile/colin-begg) at Memorial Sloan Kettering Cancer Center, focused on statistical methods for the study of etiologic heterogeneity. The first part of my research focused on comparing and contrasting existing methods for the study of etiologic heterogeneity using a simulation study and simplified data example. Next, I examined the statistical properties of our method for the study of etiologic heterogeneity to determine its ability to find the truly most etiologically heterogeneous subtype solutions under a variety of data settings. Finally, I applied the method to data from the Carolina Breast Cancer Study, and explored additional methodological challenges that exist in a real data analysis.

### Selected publications

The below publications represent my work to date on the topic of statistical methods for the study of etiologic heterogeneity:

**Zabor, E. C.**, Seshan, V. E., Wang, S., & Begg, C. B. (2021). Validity of a method for
identifying disease subtypes that are etiologically heterogeneous. *Stat Methods Med Res*, 30(9), 2045-2056. doi:10.1177/09622802211032704

Benefield, H. C., **Zabor, E. C.**, Shan, Y., Allott, E. H., Begg, C. B., & Troester, M. A. (2019). Evidence for Etiologic Subtypes of Breast Cancer in the Carolina Breast Cancer Study. *Cancer Epidemiol Biomarkers Prev*, 28(11), 1784-1791. 

**Zabor, E. C.** (2019). riskclustr: Functions to Study Etiologic Heterogeneity. *Journal of Open Source Software*, 4(35): 1269.

**Zabor, E. C.**, & Begg, C. B. (2017). A comparison of statistical methods for the study of etiologic heterogeneity. *Stat Med*, 36(25), 4050-4060.

Mauguen, A., **Zabor, E. C.**, Thomas, N. E., Berwick, M., Seshan, V. E., & Begg, C. B.(2017). Defining Cancer Subtypes With Distinctive Etiologic Profiles: An Application to the Epidemiology of Melanoma. *J Am Stat Assoc*, 112(517), 54-63.

Begg, C. B., Rice, M. S., **Zabor, E. C.**, & Tworoger, S. S. (2017). Examining the common aetiology of serous ovarian cancers and basal-like breast cancers using double primaries. *Br J Cancer*.

Begg, C. B., Orlow, I., **Zabor, E. C.**, Arora, A., Sharma, A., Seshan, V. E., Bernstein, J. L. (2015). Identifying Etiologically Distinct Sub-Types of Cancer: A Demonstration Project Involving Breast Cancer. *Cancer Med*, 4(9), 1432-1439.

Begg, C. B., Seshan, V. E., **Zabor, E. C.**, Furberg, H., Arora, A., Shen, R., . . . Hsieh, J. J. (2014). Genomic investigation of etiologic heterogeneity: methodologic challenges. *BMC Med Res Methodol*, 14, 138.

Begg, C. B., **Zabor, E. C.**, Bernstein, J. L., Bernstein, L., Press, M. F., Seshan, V. E. (2013). A conceptual and methodological framework for investigating etiologic heterogeneity. *Stat Med*, 32(29), 5039-5052.